### ISSUE TITLE
The log level setting in config.yml doesn't affect uvicorn

### ISSUE THREAD

**Issue by ghost** [opsdis/monitor-exporter#27]
Log level is set to level: WARNING in config.yml but uvicorn.acces is still logging at the INFO level. We get more than 2k rows every minute. 
{"timestamp": "2022-04-29T07:16:14.912731Z", "level": "INFO", "name": "uvicorn.access", "message": "127.0.0.1:46514 - \"GET /metrics?target=*** HTTP/1.1\" 200"}

**Comment by thenodon** [comment]
Thanks for the bug report. This is now fixed and available in release v1.3.1

**Comment by ghost** [comment]
Still get the same logging from uvicorn. Started by: gunicorn --access-logfile /dev/null -b localhost:9631 -k uvicorn.workers.UvicornWorker "monitor_exporter.main:create_app()"

**Comment by thenodon** [comment]
When you using WSGI or ASGI containers to run your code you have to check the different frameworks documentation how to control their respective  loggers, e,g, for gunicorn checkout https://docs.gunicorn.org/en/stable/settings.html. 
The fix that was done in 1.3.1 just manage how monitor-exporter mange it own loggers and the quart loggers. So even if you have configured monitor-exporter loggers to use warning you still have to configure gunicorn loggers.
